#! /bin/sh

pkill sxhkd 
sxhkd &


pkill picom
picom -f --daemon --config $HOME/.config/picom.conf

pkill polybar
$HOME/.config/polybar/material/launch.sh --blocks


bspc monitor HDMI-1 -d I II III IV 
bspc monitor eDP-1 -d V VI VII VIII 

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding         40
bspc config bottom_padding       0

bspc config split_ratio         0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
