#! /bin/sh

pkill sxhkd
sxhkd &

pkill feh
feh --bg-fill $HOME/.config/i3/wallpapers/bg_0.jpg

pkill picom
picom -f --daemon --config $HOME/.config/picom.conf

pkill polybar
$HOME/.config/polybar/launch.sh

bspc monitor HDMI-1 -d I II III IV
bspc monitor eDP-1 -d V VI VII VIII

bspc config focused_border_color "#ff79c6"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config border_width 2
bspc config window_gap 5
bspc config top_padding 40
bspc config bottom_padding 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
