#!/usr/bin/env bash

# source "$DOTLY_PATH/scripts/core/_main.sh"
# source "$DOTFILES_PATH/scripts/install/utils/install.sh"

sudo apt -y install software-properties-common

sudo apt update
sudo apt upgrade -y
sudo apt-get -y install git git-lfs git-delta tldr tmux python3-pip python3-venv btop wget luarocks xsel rofi xclip xdotool ripgrep coreutils locate ranger kitty

exit 0
