#!/bin/bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"


cd /tmp
curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh | bash

log::note "Ghostty installed ✅"

exit 0
