#!/bin/bash

set -eu pipefail

# source "$DOTLY_PATH/scripts/core/_main.sh"
# source "$DOTFILES_PATH/scripts/install/utils/install.sh"


sudo apt install -y autoconf build-essential git stow tmux tree vim-nox feh i3blocks i3lock i3status sakura suckless-tools
pip install autotiling --break-system-packages
log::note("i3 window manager installed ✅")
