#!/usr/bin/env bash

set -eu pipefail

# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install -y golang-go

go install github.com/jesseduffield/lazydocker@latest

echo "lazydocker installed 👌"

exit 0
