#!/usr/bin/env bash

set -eu pipefail

# source "$DOTLY_PATH/scripts/core/_main.sh"
# source "$DOTFILES_PATH/scripts/install/utils/install.sh"

##? Install Node Version Manager
#?? 1.0.0
##?
##? Usage:
##?   sdkman

curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash

log::note("lazydocker installed ✅")
