#!/usr/bin/env bash

set -eu pipefail

# source "$DOTLY_PATH/scripts/core/_main.sh"
# source "$DOTFILES_PATH/scripts/install/utils/install.sh"

##? Install Zellij
#?? 1.0.0
##?
##? Usage:
##?   zellij

# docs::parse "$@"

sudo apt install -y curl \
    gnupg ca-certificates git \
    gcc-multilib g++-multilib cmake libssl-dev pkg-config \
    libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev \
    libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev \
    libxcursor-dev


cargo install --git https://github.com/neovide/neovide
