#!/usr/bin/env bash

curl -fsSL https://opencode.ai/install | bash

echo "Opencode installed successfully!"

curl -fsSL https://plannotator.ai/install.sh | bash

echo "Plannotator plugin installed successfully!"
