#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

echo "🚀 Welcome to the jvegaf/dotfiles installer!"
echo "-------------------------------------------------"
echo

if grep -qEi "(archlinux)" /proc/version &> /dev/null ; then
    echo "Installing previuos dependencies"
    sudo pacman -S git base-devel rust --noconfirm --needed
else 
    echo "Installing previuos dependencies"
    sudo apt-get update && sudo apt-get install -y build-essential rustc cargo fzf fonts-powerline
fi

export PATH="$HOME/.cargo/bin:$PATH"
cargo install docpars bat git-delta

export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

git clone --recurse-submodules -j8 --depth 1 https://github.com/jvegaf/dotfiles.git "$DOTFILES_PATH"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"

echo "Installing dotly 🌚"
"$DOTLY_PATH/bin/dot" self install

echo "Installing Linux Packages"
"$DOTFILES_PATH/bin/dot" self install

