#!/usr/bin/env bash

set -euo pipefail


export DOTFILES_PATH="$HOME/.dotfiles"

export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"

echo "Installing dotly 🌚"
"$DOTLY_PATH/bin/dot" self install


echo "Symlinks apply"
"$DOTLY_PATH/bin/dot" symlinks apply


echo "Installing Linux Packages"
"$DOTLY_PATH/bin/dot" install common-pkgs
"$DOTLY_PATH/bin/dot" install neovim-stable
"$DOTLY_PATH/bin/dot" install mise
"$DOTLY_PATH/bin/dot" install fastfetch
"$DOTLY_PATH/bin/dot" install starship
"$DOTLY_PATH/bin/dot" install uvx
"$DOTLY_PATH/bin/dot" install opencode
"$DOTLY_PATH/bin/dot" install 1password
"$DOTLY_PATH/bin/dot" install docker
"$DOTLY_PATH/bin/dot" install github-cli
"$DOTLY_PATH/bin/dot" self install_custom

