#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/keyboard/utils/fix.sh"

##? Fix the numlock bug in Xubuntu
#?? 1.0.0
##?
##? Usage:
##?   numlock_fix

docs::parse "$@"

fix_unlock
log::note "Numlock disabled 🔓"
