#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Swap caps and esc
#?? 1.0.0
##?
##? Usage:
##?   swap_caps_esc

docs::parse "$@"

setxkbmap -option caps:swapescape

log::note "Caps and esc swapped "
