#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/setup/utils/setup.sh"


##? Install Linux 🐧 needed packages
#?? 1.0.0
##?
##? Usage:
##?   setup

docs::parse "$@"



log::note "Installing Linux 🐧 custom packages"

install_linux_custom

log::note "Installing Linux 🐧 AUR packages"

install_aur_packages

log::note "Installing Linux 🐧 extras"

install_linux_extra

#log::note "Installing python packages"
#pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt" || true
#pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt"

#log::note "Installing php packages"
#composer global install

#log::note "Installing npm packages"
#xargs sudo npm install -g <"$DOTFILES_PATH/langs/js/global_modules.txt"

#log::note "Setting ZSH as the default shell"
#sudo usermod -s "$(which zsh)"
# chsh -s "$(command -v zsh)"



