#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/dconf/utils/changes.sh"

##? Restore Cinnamon dconf
#?? 1.0.0
##?
##? Usage:
##?    restore
docs::parse "$@"

log::note "Restoring Cinnamon changes..."

restore_changes

log::note "Done!"


