#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
LIST_FILE="${SCRIPT_DIR}/flatpak_apps.txt"
echo "# Flatpak installation dump"
rm -rf $LIST_FILE
flatpak list --app --columns=application > $LIST_FILE

echo
echo "Archivo generado: $LIST_FILE"
