#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Setup nvidia 1660 config files to manage brightness 
#?? 1.0.0
##?
##? Usage:
##?   setup_nvidia_desktop
docs::parse "$@"

sudo add-apt-repository ppa:rockowitz/ddcutil -y
sudo apt-get update

sudo apt-get install -y ddcutil

config_path="$DOTFILES_PATH/os/linux/configs/nvidia_desktop"

sudo cp "$config_path/90-nvidia_i2c.conf" "/etc/X11/xorg.conf.d/"
sudo cp "$config_path/60-i2c-tools.rules" "/lib/udev/rules.d/"
