#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"


##? Install the dotfiles
#?? 1.0.0
##?
##? Usage:
##?   install

docs::eval "$@"

"$DOTFILES_PATH/bin/dot" self update

if platform::is_macos; then
  log::note "Installing MacOS  custom packages"

  install_macos_custom
fi

if platform::is_linux; then
  log::note "Installing Linux 🐧 custom packages"

  install_linux_custom
  install_aur_packages
  log::note "Installing Linux 🐧 extras"

  install_linux_extra
fi

#log::note "Installing python packages"
#pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt" || true
#pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt"

#log::note "Installing php packages"
#composer global install

#log::note "Installing npm packages"
#xargs sudo npm install -g <"$DOTFILES_PATH/langs/js/global_modules.txt"

#log::note "Setting ZSH as the default shell"
#sudo usermod -s "$(which zsh)"
# chsh -s "$(command -v zsh)"



