#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/fonts-setup.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"

##? Install Node Version Manager
#?? 1.0.0
##?
##? Usage:
##?   install_nvm

docs::parse "$@"

curl -o https://raw.githubusercontent.com/nvm-sh/v0.40.1/install | bash
