export DOTFILES_PATH="$HOME/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export DOTLY_THEME="codely"
# export ZIM_HOME="$DOTFILES_PATH/shell/zsh/.zim"
export ZIM_HOME="$DOTLY_PATH/modules/zimfw"
export PATH="/usr/bin/flutter/bin:$PATH"
